WR422914 Subplugin refactor
catalyst/moodle-local_assessfreq pull request #161
Opened 2024-11-28 09:08 UTC by SimonThornett

Taken from the README.md:

Post version `2024040300` this plugin was completely refactored to support more reports and modules.
In addition the report now loads in a tabbed format instead of in different locations.

Each report is now a subplugin within the `report` directory
The subplugins report class should extend from the \local_assessfreq\report_base class

Capability checks were reworked to be relative to the location that they are being loading from. The initial version
has the following capabilities:

- local/assessfreq:view
- assessfreqreport/activity_dashboard:view
- assessfreqreport/activities_in_progress:view
- assessfreqreport/heatmap:view
- assessfreqreport/summary_graphs:view

however each future subplugin can define their own access checks by using the abstract `has_access` method.
Accessing the reports from a course (link now added to the course context menu under reports) will do the capability check at the
course context level, otherwise system level will be used.

The reports themselves should also be restricted based on the $PAGE->course if it is not the SITEID as this is set
during the intial load of the index.php file.

Each module is now a subplugin within the `source` directory
The subplugins source class should extend from the \local_assessfreq\source_base class

2024-11-28 22:43 UTC, dmitriim commented
Hi @SimonThornett 
Very exciting changes. However, can you please apply the changes to the latest branch of the plugin first MOODLE_403_STABLE and then backport as required to later versions?

2024-12-02 08:33 UTC, SimonThornett commented
Hi @dmitriim,

Not a problem. I know that there are some compatibility issues with the modal since 4.2, but I'll rebase this from 403, add in the modal fix that I have for that branch and add some version based loading for the different modal JS so that we can have one version that covers all.

2024-12-02 21:01 UTC, dmitriim commented
@SimonThornett yeah. Modal factory has been deprecated. See this example of how to deal with that https://github.com/catalyst/moodle-local_assessfreq/commit/a18328d051eb6783a5964c8b82ab4770186c8807

2024-12-02 21:05 UTC, dmitriim commented
@SimonThornett do you have ETA for this work to be completed? It's a big change so all other PRs can be affected as well as you'd need to rebase everything anything lands. I'm really keen to get this landed ASAP to make everyone life easier. Happy to review it when ready.

2024-12-03 08:09 UTC, SimonThornett commented
Thanks @dmitriim, I actually did a similar thing on the 4.4 branch I was working on [here](https://github.com/catalyst/moodle-local_assessfreq/blob/WR422914-404/report/activity_dashboard/amd/src/form_modal.js#L65).

I'm working on the update as we speak and my colleague @sarahjcotton will likely be able to pick up the review as she is also familiar with the work that was done here having done the original specification. Would be great for another pair of eyes, but I appreciate it is a substantial piece of work.

I'm just working on a couple of additional improvements to performance and functionality and I'll update the branch.

2024-12-03 16:04 UTC, SimonThornett commented
Hey @dmitriim,

I've updated the branch to base off of the 403 stable. I haven't passed it over for internal review yet as I'm just sorting the PHP Unit tests. Those can be reviewed separately so I'll push those as a different commit and ask someone our side to have a look at the current commit.
Regarding UA testing, Jakub has completed a number of rounds on the WR #422914 and attached the test sheet "local_assesfreq test sheet.xlsx"

2024-12-05 09:38 UTC, SimonThornett commented
Latest commit contains the updated unit tests and behat tests. All unit tests pass with the following output:

Time: 07:41.730, Memory: 137.00 MB
OK (53 tests, 298 assertions)
Process finished with exit code 0

behat pass 23 of 23 tests in 33 seconds

2024-12-09 12:01 UTC, daledavies commented on classes/frequency.php
> +    public function get_site_events(int $courseid, string $module = 'all', int $from = 0, int $to = 0, bool $cache = true): array {
Is $courseid used in this method?

2024-12-09 12:16 UTC, daledavies commented on source/assign/classes/source.php
> +        $assign->overridecount = count($overridenparticipants);
I can't find this property in the assign() class

2024-12-09 12:16 UTC, daledavies commented on source/assign/classes/source.php
> +        $assign->submissions = $submissions;
Same for these and a bunch of others too.

2024-12-09 12:29 UTC, daledavies commented on classes/source_base.php
> +    public function __construct() {
Same for this

2024-12-09 12:33 UTC, daledavies commented on classes/report_base.php
> +    }
As these are not actually getters, would they be better named as something like `add_required_js()` etc?

2024-12-09 12:34 UTC, daledavies commented on classes/source_base.php
> +    protected function get_required_js() {
Same as above

2024-12-09 12:36 UTC, daledavies commented on classes/task/data_process.php
> +        //mtrace('local_assessfreq: Processing user events finished in: ' . $actionduration . ' seconds');
This appears to have been left in by accident?

2024-12-16 14:23 UTC, daledavies requested changes
### Worth addressing CI failures

- There seem to be cases where docblock and function definitiion don't match, parameters/return types missing or not matching etc.
- Instances of spaces before colons when defining return types for functions (report_base and source_base for example).
- I'm not 100% sure about the use of @inheritDoc.
- The new functions in lib.php should use frankenstyle prefix https://moodledev.io/general/development/policies/codingstyle#functions-and-methods. Or could they be moved into a more appropriate class?
- Multiple files complaining about not ending with blank line.
- A few instances where blocks of code are commented out.
- Test failures etc.

### General

There are a lot of references (guarded my `method_exists` checks) to methods that do not exist in the `report_base` or `source_base` abstract classes. I wonder if you could create interfaces for these, then you have something that defines the method signature contract. At the moment you can't be sure that a subplugin has defined one of these methods correctly when you are calling it. Rather than using `method_exists` you could check to see if the class inherits the interface etc.

I've also made a few notes around the place where I think you could abstract some areas of repeated code.

### PHP 8.2 compatibility

There are areas where dynamic properties are added to classes, in some cases this is for objects that will probably be instances of `stdClass` (`quiz_settings::get_quiz()` for example returns  `stdClass`), but others appear to be instances of actual classes (like `assign()`). I'm wondering if this might cause issues with PHP 8.2?

2024-12-16 14:23 UTC, daledavies commented on lib.php
> +function get_sources($ignoreenabled = false, $requiredmethod = '') : array {
Should this use a frankenstyle prefix?

2024-12-16 14:23 UTC, daledavies commented on lib.php
> +function get_months_ordered() : array {
Should this use a frankenstyle prefix?

2024-12-16 14:23 UTC, daledavies commented on lib.php
> +function get_years($preference) : array {
Should this use a frankenstyle prefix?

2024-12-16 14:23 UTC, daledavies commented on lib.php
> +function get_modules($preferences, $requiredmethod= '') : array {
Should this use a frankenstyle prefix?

2024-12-16 14:23 UTC, daledavies commented on lib.php
> +function get_loggedin_users(array $userids): stdClass {
Should this use a frankenstyle prefix?

2024-12-24 21:18 UTC, aspark21 commented on version.php
> +$plugin->release = '2024040302';
you're downgrading version number and supported versions.

I think you might have squashed some changes in this commit that shouldn't have been included

2025-01-03 09:24 UTC, SimonThornett commented on version.php
> +$plugin->release = '2024040302';
Thanks for flagging that Alistair.
I'm working on the amendments to this now and will correct that. You're right that it was due to the merging of the 4.1 and 4.2 versions of the plugin that I have rebased and been working on.

2025-01-15 11:44 UTC, SimonThornett commented on classes/frequency.php
> +    public function get_site_events(int $courseid, string $module = 'all', int $from = 0, int $to = 0, bool $cache = true): array {
This is not used, but has been added to match the other dynamically called functions around it. This can be refactored in the future, but at present has been done to match the other function calls.

2025-01-15 11:44 UTC, SimonThornett commented on source/assign/classes/source.php
> +        $assign->overridecount = count($overridenparticipants);
The assign class has been replaced with a stdClass object that will allow for this and prevent issues with 8.2

2025-01-15 11:44 UTC, SimonThornett commented on source/assign/classes/source.php
> +        $assign->laststart = $laststart;
The assign class has been replaced with a stdClass object that will allow for this and prevent issues with 8.2

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_loggedin_users(array $userids): stdClass {
Updated to meet Moodle coding standards.

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_modules($preferences, $requiredmethod= '') : array {
Updated to meet Moodle coding standards.

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_years($preference) : array {
Updated to meet Moodle coding standards.

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_months_ordered() : array {
Updated to meet Moodle coding standards.

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_sources($ignoreenabled = false, $requiredmethod = '') : array {
Updated to meet Moodle coding standards.

2025-01-15 14:23 UTC, SimonThornett commented on templates/index.mustache
> +    <p>
Replaced with a bootstrap classed div.

2025-01-15 14:23 UTC, SimonThornett commented on source/quiz/version.php
> +$plugin->maturity = MATURITY_STABLE;
Updated in line with CI checks.

2025-01-15 14:23 UTC, SimonThornett commented on source/quiz/lib.php
> +function assessfreqsource_quiz_output_fragment_get_user_table($args): string {
As discussed we will pick this up in a later iteration of the project. However for the source level functions abstraction is difficult without created too many dependencies.

2025-01-15 14:23 UTC, SimonThornett commented on source/quiz/classes/source.php
> +        $quiz->overridecount = html_writer::link(
As discussed assign and quiz objects are now both stdClass objects and as such adding to the object is no longer an issue with 8.2

2025-01-15 14:23 UTC, SimonThornett commented on report/summary_graphs/classes/output/generate_assess_by_month_chart.php
> +        $chart = new $charttype();
This is validated at the settings level as the types are set to specific values (which admin settings validate) so there is no means to select a chart type that does not exist.

2025-01-15 14:23 UTC, SimonThornett commented on report/summary_graphs/classes/output/assess_by_month_student.php
> +    public function get_assess_by_month_student_chart(int $year, int $month) : array {
Updated in line with the CI checks.

2025-01-15 14:23 UTC, SimonThornett commented on report/summary_graphs/classes/output/assess_by_month.php
> +    public function get_assess_by_month_chart(int $year, int $month) : array {
Updated in line with the CI checks.

2025-01-15 14:23 UTC, SimonThornett commented on report/summary_graphs/classes/output/assess_by_activity.php
> +    public function get_assess_by_activity_chart(int $year, int $month) : array {
Updated in line with the CI checks.

2025-01-15 14:23 UTC, SimonThornett commented on report/student_search/classes/output/user_table.php
> +        //$manage .= \html_writer::link('#', $icon, [
Removed.

2025-01-15 14:23 UTC, SimonThornett commented on report/student_search/classes/output/user_table.php
> +     * @param \stdClass $row
This has been updated in line with the CI checks as discussed.

2025-01-15 14:23 UTC, SimonThornett commented on report/activities_in_progress/classes/output/renderer.php
> +    public function render_report($data) {
This has been updated in line with all of the CI checks.

2025-01-15 14:23 UTC, SimonThornett commented on ci.yml
Removed

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_modules($preferences, $requiredmethod= '') : array {
After discussing the logic it has been kept as is, but the doc block has been updated to provide more information.

2025-01-15 14:23 UTC, SimonThornett commented on lib.php
> +function get_sources($ignoreenabled = false, $requiredmethod = '') : array {
After discussing the logic it has been kept as is, but the doc block has been updated to provide more information.

2025-01-15 14:23 UTC, SimonThornett commented on db/tasks.php
> +    ]
Re-added

2025-01-15 14:23 UTC, SimonThornett commented on classes/source_base.php
> +    }
Updated function names.

2025-01-15 14:23 UTC, SimonThornett commented on classes/report_base.php
> +    }
Updated function names.

2025-01-15 14:23 UTC, SimonThornett commented on classes/source_base.php
> +    public function __construct() {
Updated to private and confirmed working in unit tests.

2025-01-15 14:23 UTC, SimonThornett commented on classes/report_base.php
> +    public function __construct() {
Updated to private and confirmed working in unit tests.

2025-02-03 15:06 UTC, daledavies commented on report/activities_in_progress/classes/output/renderer.php
> +    public function render_report($data) {
Just noting there is still an issue with the new docblock. The render_report method declares that it will return a string but the docblock shows a union type of `array|bool|string`.

Interestingly the docblock for `render_from_template()` states it will return `string|boolean` but as far as I can tell from the code it should return just a string.

I wonder if, in order not to have to return an array of charts for unit testing, there should be separate methods to generate chart data which CAN be unit tested. Leaving the renderer to compile them all into the template?

2025-02-06 09:27 UTC, SimonThornett commented on report/activities_in_progress/classes/output/renderer.php
> +    public function render_report($data) {
This has been updated to return a single type with the chart generation being done in a separate public function

2025-02-07 09:56 UTC, daledavies commented on report/activities_in_progress/classes/output/renderer.php
> +    public function render_report($data) {
This looks much better

2025-02-07 09:58 UTC, daledavies approved these changes

2025-02-14 08:43 UTC, SimonThornett commented
Thanks @daledavies.

@dmitriim, with the review done Jakub has done additional smoke testing on a 4.4 site and updated WR#440693 accordingly. The only issues on the CI runs are for 4.5 and those are core issues, not the plugin.

Let me know if you have any questions or want to have a chat about the work here.

Simon T

2025-03-21 14:46 UTC, merged